# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created: Sat Jun 14 20:21:31 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(762, 611)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_subir = QtGui.QPushButton(self.groupBox)
        self.btn_subir.setObjectName("btn_subir")
        self.horizontalLayout.addWidget(self.btn_subir)
        self.btn_bajar = QtGui.QPushButton(self.groupBox)
        self.btn_bajar.setObjectName("btn_bajar")
        self.horizontalLayout.addWidget(self.btn_bajar)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(311, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)
        self.tabla = QtGui.QTableView(self.centralwidget)
        self.tabla.setMaximumSize(QtCore.QSize(510, 16777215))
        self.tabla.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabla.setDragEnabled(False)
        self.tabla.setDragDropOverwriteMode(False)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabla.setGridStyle(QtCore.Qt.SolidLine)
        self.tabla.setCornerButtonEnabled(False)
        self.tabla.setObjectName("tabla")
        self.gridLayout.addWidget(self.tabla, 1, 0, 1, 1)
        self.info = QtGui.QWidget(self.centralwidget)
        self.info.setObjectName("info")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.info)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_image = QtGui.QLabel(self.info)
        self.lbl_image.setMinimumSize(QtCore.QSize(220, 331))
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.verticalLayout_3.addWidget(self.lbl_image)
        self.info2 = QtGui.QWidget(self.info)
        self.info2.setObjectName("info2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.info2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_title_reparto = QtGui.QLabel(self.info2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbl_title_reparto.setFont(font)
        self.lbl_title_reparto.setText("")
        self.lbl_title_reparto.setObjectName("lbl_title_reparto")
        self.verticalLayout_2.addWidget(self.lbl_title_reparto)
        self.lbl_reparto = QtGui.QLabel(self.info2)
        self.lbl_reparto.setEnabled(True)
        self.lbl_reparto.setMaximumSize(QtCore.QSize(270, 16777215))
        self.lbl_reparto.setText("")
        self.lbl_reparto.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_reparto.setScaledContents(False)
        self.lbl_reparto.setWordWrap(True)
        self.lbl_reparto.setObjectName("lbl_reparto")
        self.verticalLayout_2.addWidget(self.lbl_reparto)
        self.lbl_title_descripcion = QtGui.QLabel(self.info2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbl_title_descripcion.setFont(font)
        self.lbl_title_descripcion.setText("")
        self.lbl_title_descripcion.setObjectName("lbl_title_descripcion")
        self.verticalLayout_2.addWidget(self.lbl_title_descripcion)
        self.lbl_descripcion = QtGui.QLabel(self.info2)
        self.lbl_descripcion.setMaximumSize(QtCore.QSize(270, 16777215))
        self.lbl_descripcion.setText("")
        self.lbl_descripcion.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_descripcion.setScaledContents(False)
        self.lbl_descripcion.setWordWrap(True)
        self.lbl_descripcion.setObjectName("lbl_descripcion")
        self.verticalLayout_2.addWidget(self.lbl_descripcion)
        self.verticalLayout_3.addWidget(self.info2)
        self.gridLayout.addWidget(self.info, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Ranking Películas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Ranking", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_subir.setText(QtGui.QApplication.translate("MainWindow", "Subir", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_bajar.setText(QtGui.QApplication.translate("MainWindow", "Bajar", None, QtGui.QApplication.UnicodeUTF8))

